In [1]:
# import liberaries
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)
import matplotlib.pyplot as plt
import seaborn as sns
import os 
import openpyxl

In [2]:
# read dataset
path = os.path.join(os.getcwd(), 'data', 'DataCoSupplyChainDataset.csv')
df = pd.read_csv(path, encoding='ISO-8859-1')

In [3]:
df.head(5)

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,Customer Country,Customer Email,Customer Fname,Customer Id,Customer Lname,Customer Password,Customer Segment,Customer State,Customer Street,Customer Zipcode,Department Id,Department Name,Latitude,Longitude,Market,Order City,Order Country,Order Customer Id,order date (DateOrders),Order Id,Order Item Cardprod Id,Order Item Discount,Order Item Discount Rate,Order Item Id,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,XXXXXXXXX,Cally,20755,Holloway,XXXXXXXXX,Consumer,PR,5365 Noble Nectar Island,725.0,2,Fitness,18.251453,-66.037056,Pacific Asia,Bekasi,Indonesia,20755,1/31/2018 22:56,77202,1360,13.110000,0.04,180517,327.75,0.29,1,327.75,314.640015,91.250000,Southeast Asia,Java Occidental,COMPLETE,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,Puerto Rico,XXXXXXXXX,Irene,19492,Luna,XXXXXXXXX,Consumer,PR,2679 Rustic Loop,725.0,2,Fitness,18.279451,-66.037064,Pacific Asia,Bikaner,India,19492,1/13/2018 12:27,75939,1360,16.389999,0.05,179254,327.75,-0.80,1,327.75,311.359985,-249.089996,South Asia,Rajastán,PENDING,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,EE. UU.,XXXXXXXXX,Gillian,19491,Maldonado,XXXXXXXXX,Consumer,CA,8510 Round Bear Gate,95125.0,2,Fitness,37.292233,-121.881279,Pacific Asia,Bikaner,India,19491,1/13/2018 12:06,75938,1360,18.030001,0.06,179253,327.75,-0.80,1,327.75,309.720001,-247.779999,South Asia,Rajastán,CLOSED,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,EE. UU.,XXXXXXXXX,Tana,19490,Tate,XXXXXXXXX,Home Office,CA,3200 Amber Bend,90027.0,2,Fitness,34.125946,-118.291016,Pacific Asia,Townsville,Australia,19490,1/13/2018 11:45,75937,1360,22.940001,0.07,179252,327.75,0.08,1,327.75,304.809998,22.860001,Oceania,Queensland,COMPLETE,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,XXXXXXXXX,Orli,19489,Hendricks,XXXXXXXXX,Corporate,PR,8671 Iron Anchor Corners,725.0,2,Fitness,18.253769,-66.037048,Pacific Asia,Townsville,Australia,19489,1/13/2018 11:24,75936,1360,29.500000,0.09,179251,327.75,0.45,1,327.75,298.250000,134.210007,Oceania,Queensland,PENDING_PAYMENT,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [4]:
df.shape

(180519, 53)

### columns renaming and cleaning

In [5]:
df.columns = [col.lower().replace(' ', '_') for col in df.columns]

rename_dict = {
    'days_for_shipping_(real)': 'shipping_days_actual',
    'days_for_shipment_(scheduled)': 'shipping_days_scheduled',
    'benefit_per_order': 'profit_per_order',
    'order_date_(dateorders)': 'order_date',
    'shipping_date_(dateorders)': 'shipping_date',
    'order_item_cardprod_id': 'order_product_id',
    'product_card_id': 'product_id'
}

df.rename(columns=rename_dict, inplace=True)

In [6]:
df[['product_status', 'product_image', 'customer_password', 'customer_email']].head(5)

,product_status,product_image,customer_password,customer_email
0,0,http://images.acmesports.sports/Smart+watch,XXXXXXXXX,XXXXXXXXX
1,0,http://images.acmesports.sports/Smart+watch,XXXXXXXXX,XXXXXXXXX
2,0,http://images.acmesports.sports/Smart+watch,XXXXXXXXX,XXXXXXXXX
3,0,http://images.acmesports.sports/Smart+watch,XXXXXXXXX,XXXXXXXXX
4,0,http://images.acmesports.sports/Smart+watch,XXXXXXXXX,XXXXXXXXX

In [7]:
# Redundancy and useless columns cleaning
df.drop(columns=['product_status', 'product_image', 'customer_password', 'customer_email', 
                 'order_customer_id', 'order_item_product_price', 'order_profit_per_order', 
                 'sales_per_customer', 'product_category_id', 'order_product_id'], inplace=True)

### data types handling

In [9]:
objects = ['category_id', 'customer_id', 'department_id', 'order_id', 'order_item_id', 'product_id', 
           'customer_zipcode', 'order_zipcode' ]
times = ['order_date', 'shipping_date']
df[objects] = df[objects].astype(str)
df[times] = df[times].apply(pd.to_datetime)

In [14]:
# space deleting from the values
df = df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

### NaN Handling

In [15]:
df.isnull().sum().sort_values(ascending=False).head()

product_description    180519
customer_lname              8
type                        0
profit_per_order            0
delivery_status             0
dtype: int64

In [16]:
# product_description, order_zipcode
df.drop(columns=['product_description', 'order_zipcode'], inplace=True)

In [17]:
# customer_lname
mask = df['customer_lname'].isna()
lname_most = df.groupby('customer_city')['customer_lname'].transform(lambda x : x.mode()[0] if not x.mode().empty else np.nan)
df['customer_lname'] = df['customer_lname'].fillna(lname_most)
df.loc[mask, 'customer_lname']

41422      Smith
50447      Smith
86260      Smith
92621      Smith
97530      Smith
120404     Smith
166129     Smith
167119    Brooks
Name: customer_lname, dtype: object

In [18]:
# customer_zipcode
df['customer_zipcode'] = df['customer_zipcode'].replace('nan', np.nan)
mask = df['customer_zipcode'].isna()
cols_target = ['customer_zipcode', 'customer_state', 'customer_city', 'customer_street']
cols_source = ['customer_state', 'customer_city', 'customer_street']
zip_nan = df.loc[mask]
zip_nan[cols_target]

      customer_zipcode customer_state customer_city customer_street
35704              NaN          95758            CA       Elk Grove
46440              NaN          95758            CA       Elk Grove
82511              NaN          91732            CA        El Monte

In [19]:
df.loc[mask, cols_target] = df.loc[mask, cols_source].assign(street_nan=np.nan).values
df.loc[mask, cols_target]

      customer_zipcode customer_state customer_city customer_street
35704            95758             CA     Elk Grove             NaN
46440            95758             CA     Elk Grove             NaN
82511            91732             CA      El Monte             NaN

In [20]:
street_most = df.groupby('customer_city')['customer_street'].transform(
    lambda x : x.mode()[0] if not x.mode().empty else np.nan)

df['customer_street'] = df['customer_street'].fillna(street_most)
df.loc[mask, cols_target]

      customer_zipcode customer_state customer_city       customer_street
35704            95758             CA     Elk Grove       4096 Amber Bend
46440            95758             CA     Elk Grove       4096 Amber Bend
82511            91732             CA      El Monte  2845 Jagged Oak Vale

### Recategorization

In [23]:
df.select_dtypes(include='object').nunique().sort_values()

customer_country         2
customer_segment         3
delivery_status          4
type                     4
shipping_mode            4
market                   5
order_status             9
department_id           11
department_name         11
order_region            23
customer_state          44
category_name           50
category_id             51
product_id             118
product_name           118
order_country          164
customer_city          562
customer_fname         782
customer_zipcode       997
order_state           1089
customer_lname        1109
order_city            3597
customer_street       6951
customer_id          20652
order_id             65752
order_item_id       180519
dtype: int64

In [24]:
mapping_df = pd.read_excel('products_list.xlsx') 

unique_cats = mapping_df['new_category'].unique()
cat_to_id = {name: i+1 for i, name in enumerate(unique_cats)}
mapping_df['new_category_id'] = mapping_df['new_category'].map(cat_to_id)

df = df.merge(mapping_df, on='product_name', how='left')

df = df.drop(['category_id', 'category_name'], axis=1)

In [25]:
df['new_category_id'] = df['new_category_id'].astype(object)
df = df.rename(columns={
    'new_category': 'category_name',
    'new_category_id': 'category_id'
})

df.select_dtypes(include='object').nunique().sort_values()

customer_country         2
customer_segment         3
delivery_status          4
type                     4
shipping_mode            4
market                   5
order_status             9
department_id           11
department_name         11
order_region            23
category_name           39
category_id             39
customer_state          44
product_id             118
product_name           118
order_country          164
customer_city          562
customer_fname         782
customer_zipcode       997
order_state           1089
customer_lname        1109
order_city            3597
customer_street       6951
customer_id          20652
order_id             65752
order_item_id       180519
dtype: int64

### Data Spliting

In [26]:
def create_modular_tables(df):
    customers = df[[
        'customer_id', 'customer_fname', 'customer_lname', 'customer_segment', 
        'customer_street', 'customer_zipcode', 'customer_city', 'customer_state', 'customer_country', 'latitude', 'longitude'
    ]].drop_duplicates(subset=['customer_id'])

    products = df[[
        'product_id', 'product_name', 'product_price', 'category_id'
    ]].drop_duplicates(subset=['product_id'])

    categories = df[[
        'category_id', 'category_name', 'department_id', 'department_name'
    ]].drop_duplicates(subset=['category_id'])

    orders = df[[
        'order_id', 'customer_id', 'order_date', 'order_status', 
        'type', 'market', 'order_region', 'order_city', 'order_state', 'order_country'
    ]].drop_duplicates(subset=['order_id'])

    items = df[[
        'order_item_id', 'order_id', 'product_id', 'order_item_quantity', 
        'order_item_discount', 'order_item_discount_rate', 'sales', 
        'order_item_total', 'profit_per_order', 'order_item_profit_ratio'
    ]]

    shipping = df[[
        'order_id', 'shipping_date', 'shipping_days_actual', 
        'shipping_days_scheduled', 'shipping_mode', 'delivery_status', 'late_delivery_risk'
    ]].drop_duplicates(subset=['order_id'])

    return customers, products, categories, orders, items, shipping

customers, products, categories, orders, items, shipping = create_modular_tables(df)

In [ ]:
output_dir = 'processed_data'
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

customers.to_csv(f'{output_dir}/customers.csv', index=False)
products.to_csv(f'{output_dir}/products.csv', index=False)
categories.to_csv(f'{output_dir}/categories.csv', index=False)
orders.to_csv(f'{output_dir}/orders.csv', index=False)
items.to_csv(f'{output_dir}/order_items.csv', index=False)
shipping.to_csv(f'{output_dir}/shipping.csv', index=False)

In [36]:
df['order_date'] = pd.to_datetime(df['order_date'])

stability_start = '2015-01-01'
stability_end = '2017-09-01'
recession_end = '2018-01-30' 

stability_df = df[(df['order_date'] >= stability_start) & (df['order_date'] < stability_end)]
recession_df = df[(df['order_date'] >= stability_end) & (df['order_date'] < recession_end)]

monthly_sales_stb = stability_df['sales'].sum() / 32
monthly_sales_rec = recession_df['sales'].sum() / 5
monthly_cost_stb = stability_df['product_price'].sum() / 32
monthly_cost_rec = recession_df['product_price'].sum() / 5
monthly_profit_stb = stability_df['profit_per_order'].sum() / 32
monthly_profit_rec = recession_df['profit_per_order'].sum() / 5

sales_drop_pct = ((monthly_sales_stb - monthly_sales_rec) / monthly_sales_stb) * 100
cost_drop_pct = ((monthly_cost_stb - monthly_cost_rec) / monthly_cost_stb) * 100
profit_drop_pct = ((monthly_profit_stb - monthly_profit_rec) / monthly_profit_stb) * 100

margin_stb = monthly_profit_stb / monthly_sales_stb
margin_rec = monthly_profit_rec / monthly_sales_rec
target_sales = monthly_sales_stb 

profit_from_stb_part = (target_sales * 0.95) * margin_stb
profit_from_rec_part = (target_sales * 0.05) * margin_rec
hybrid_monthly_profit = profit_from_stb_part + profit_from_rec_part

In [37]:
print(f"--- فترة الاستقرار (شهرياً) ---")
print(f"المبيعات: ${monthly_sales_stb:,.2f}")
print(f"التكلفة الحقيقية: ${monthly_cost_stb:,.2f}")

print(f"\n--- فترة الركود (شهرياً) ---")
print(f"المبيعات: ${monthly_sales_rec:,.2f}")
print(f"التكلفة الحقيقية: ${monthly_cost_rec:,.2f}")

print(f"\n--- معدلات الهبوط---")
print(f"نسبة الهبوط في الأداء المالي: {sales_drop_pct:.2f}%")
print(f"نسبة الهبوط في التكلفة: {cost_drop_pct:.2f}%")
print(f"نسبة الهبوط في الربح: {profit_drop_pct:.2f}%")
print("-" * 30)

print(f"نسبة ربح الاستقرار الفعلية: {margin_stb:.2%}")
print(f"نسبة ربح الركود الفعلية: {margin_rec:.2%}")
print("-" * 30)

print(f"الربح الشهري الصافي فترة الاستقرار: ${monthly_profit_stb:,.2f}")
print(f"الربح الشهري الصافي فترة الركود: ${monthly_profit_rec:,.2f}")
print(f"الربح الشهري المتوقع (نموذج 95/5): ${hybrid_monthly_profit:,.2f}")

--- فترة الاستقرار (شهرياً) ---
المبيعات: $1,034,515.33
التكلفة الحقيقية: $692,042.60

--- فترة الركود (شهرياً) ---
المبيعات: $730,189.13
التكلفة الحقيقية: $664,099.33

--- معدلات الهبوط---
نسبة الهبوط في الأداء المالي: 29.42%
نسبة الهبوط في التكلفة: 4.04%
نسبة الهبوط في الربح: 28.00%
------------------------------
نسبة ربح الاستقرار الفعلية: 10.76%
نسبة ربح الركود الفعلية: 10.98%
------------------------------
الربح الشهري الصافي فترة الاستقرار: $111,360.08
الربح الشهري الصافي فترة الركود: $80,181.76
الربح الشهري المتوقع (نموذج 95/5): $111,472.06